Repository AY2223S1-CS2103T-T11-3/tp, pull requests merged in 2022-10, with the labels that each got.

#87 Add Lesson classes
  src/main/java/jarvis/logic/commands/AddStudentCommand.java
  src/main/java/jarvis/logic/commands/EditStudentCommand.java
  src/main/java/jarvis/logic/parser/AddStudentCommandParser.java
  src/main/java/jarvis/logic/parser/CliSyntax.java
  src/main/java/jarvis/logic/parser/EditStudentCommandParser.java
  src/main/java/jarvis/logic/parser/ParserUtil.java
  src/main/java/jarvis/model/Consult.java
  src/main/java/jarvis/model/Lesson.java
  src/main/java/jarvis/model/LessonAttendance.java
  src/main/java/jarvis/model/LessonDesc.java
  src/main/java/jarvis/model/LessonNotes.java
  src/main/java/jarvis/model/MasteryCheck.java
  src/main/java/jarvis/model/MatricNum.java
  src/main/java/jarvis/model/Student.java
  src/main/java/jarvis/model/Studio.java
  src/main/java/jarvis/model/StudioParticipation.java
  src/main/java/jarvis/model/TimePeriod.java
  src/main/java/jarvis/model/UniqueStudentList.java
  src/main/java/jarvis/model/util/SampleStudentUtil.java
  src/main/java/jarvis/storage/JsonAdaptedStudent.java
  src/main/java/jarvis/ui/StudentCard.java
  src/main/resources/view/StudentCard.fxml
  src/test/data/JsonSerializableStudentBookTest/duplicateStudentStudentBook.json
  src/test/data/JsonSerializableStudentBookTest/invalidStudentStudentBook.json
  src/test/data/JsonSerializableStudentBookTest/typicalStudentsStudentBook.json
  src/test/java/jarvis/logic/LogicManagerTest.java
  src/test/java/jarvis/logic/commands/AddStudentCommandTest.java
  src/test/java/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/jarvis/logic/commands/DeleteStudentCommandTest.java
  src/test/java/jarvis/logic/commands/EditStudentCommandTest.java
  src/test/java/jarvis/logic/commands/ListStudentCommandTest.java
  src/test/java/jarvis/logic/parser/AddStudentCommandParserTest.java
  src/test/java/jarvis/logic/parser/StudentBookParserTest.java
  src/test/java/jarvis/model/student/StudentTest.java
  src/test/java/jarvis/storage/JsonAdaptedStudentTest.java
  src/test/java/jarvis/testutil/EditStudentDescriptorBuilder.java
  src/test/java/jarvis/testutil/StudentBuilder.java
  src/test/java/jarvis/testutil/StudentUtil.java
  src/test/java/jarvis/testutil/TypicalStudents.java
Labels: priority.High

#88 Enable assertions
  build.gradle
  src/main/java/jarvis/MainApp.java
Labels: type.Task

#89 Support add lesson and delete lesson commands
  src/main/java/jarvis/MainApp.java
  src/main/java/jarvis/commons/core/Messages.java
  src/main/java/jarvis/logic/commands/AddConsultCommand.java
  src/main/java/jarvis/logic/commands/AddMasteryCheckCommand.java
  src/main/java/jarvis/logic/commands/AddStudioCommand.java
  src/main/java/jarvis/logic/commands/DeleteLessonCommand.java
  src/main/java/jarvis/logic/parser/AddConsultCommandParser.java
  src/main/java/jarvis/logic/parser/AddMasteryCheckCommandParser.java
  src/main/java/jarvis/logic/parser/AddStudioCommandParser.java
  src/main/java/jarvis/logic/parser/CliSyntax.java
  src/main/java/jarvis/logic/parser/DeleteLessonCommandParser.java
  src/main/java/jarvis/logic/parser/DeleteStudentCommandParser.java
  src/main/java/jarvis/logic/parser/JarvisParser.java
  src/main/java/jarvis/logic/parser/ParserUtil.java
  src/main/java/jarvis/model/LessonAttendance.java
  src/main/java/jarvis/model/LessonBook.java
  src/main/java/jarvis/model/Model.java
  src/main/java/jarvis/model/ModelManager.java
  src/main/java/jarvis/model/ReadOnlyLessonBook.java
  src/main/java/jarvis/model/ReadOnlyUserPrefs.java
  src/main/java/jarvis/model/StudentBook.java
  src/main/java/jarvis/model/TaskBook.java
  src/main/java/jarvis/model/TimePeriod.java
  src/main/java/jarvis/model/UniqueLessonList.java
  src/main/java/jarvis/model/UserPrefs.java
  src/main/java/jarvis/model/exceptions/DuplicateLessonException.java
  src/main/java/jarvis/model/exceptions/LessonClashException.java
  src/main/java/jarvis/model/exceptions/LessonNotFoundException.java
  src/test/java/jarvis/logic/commands/AddStudentCommandTest.java
Labels: priority.High

#90 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteStudentSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MarkTaskSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteStudentSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MarkTaskSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Task

#100 Expanded Lesson UI
  src/main/java/jarvis/logic/commands/AddConsultCommand.java
  src/main/java/jarvis/logic/commands/AddMasteryCheckCommand.java
  src/main/java/jarvis/logic/commands/AddNoteCommand.java
  src/main/java/jarvis/logic/commands/AddParticipationCommand.java
  src/main/java/jarvis/logic/commands/AddStudioCommand.java
  src/main/java/jarvis/logic/commands/DeleteNoteCommand.java
  src/main/java/jarvis/logic/commands/ListLessonCommand.java
  src/main/java/jarvis/logic/commands/MarkStudentCommand.java
  src/main/java/jarvis/logic/commands/UnmarkStudentCommand.java
  src/main/java/jarvis/logic/parser/AddConsultCommandParser.java
  src/main/java/jarvis/logic/parser/AddMasteryCheckCommandParser.java
  src/main/java/jarvis/logic/parser/AddStudioCommandParser.java
  src/main/java/jarvis/logic/parser/CliSyntax.java
  src/main/java/jarvis/logic/parser/JarvisParser.java
  src/main/java/jarvis/logic/parser/ParserUtil.java
  src/main/java/jarvis/model/Consult.java
  src/main/java/jarvis/model/GradeProfile.java
  src/main/java/jarvis/model/Lesson.java
  src/main/java/jarvis/model/LessonAttendance.java
  src/main/java/jarvis/model/LessonBook.java
  src/main/java/jarvis/model/LessonNotes.java
  src/main/java/jarvis/model/MasteryCheck.java
  src/main/java/jarvis/model/ModelManager.java
  src/main/java/jarvis/model/Student.java
  src/main/java/jarvis/model/Studio.java
  src/main/java/jarvis/model/StudioParticipation.java
  src/main/java/jarvis/model/Task.java
  src/main/java/jarvis/model/TimePeriod.java
  src/main/java/jarvis/model/UniqueLessonList.java
  src/main/java/jarvis/model/UniqueStudentList.java
  src/main/java/jarvis/model/UniqueTaskList.java
  src/main/java/jarvis/storage/JsonAdaptedTask.java
  src/main/java/jarvis/ui/ExpandedLessonCard.java
  src/main/java/jarvis/ui/ExpandedLessonListPanel.java
  src/main/java/jarvis/ui/ExpandedStudentListPanel.java
  src/main/java/jarvis/ui/ExpandedTaskCard.java
  src/main/java/jarvis/ui/ExpandedTaskListPanel.java
  src/main/java/jarvis/ui/MainWindow.java
  src/main/resources/view/ExpandedLessonCard.fxml
  src/main/resources/view/ExpandedLessonList.css
  src/main/resources/view/ExpandedLessonListPanel.fxml
  src/main/resources/view/ExpandedLessonTable.css
  src/main/resources/view/ExpandedStudentCard.fxml
  src/main/resources/view/ExpandedStudentTable.css
  src/main/resources/view/ExpandedTaskCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#103 Set limit for number of students
  src/main/java/jarvis/logic/commands/AddStudentCommand.java
  src/main/java/jarvis/model/StudentBook.java
  src/main/java/jarvis/model/UniqueStudentList.java
  src/main/java/jarvis/model/exceptions/DuplicateLessonException.java
  src/main/java/jarvis/model/exceptions/DuplicateStudentException.java
  src/main/java/jarvis/model/exceptions/MaxStudentsExceededException.java
Labels: priority.Medium

#106 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/jarvis/logic/commands/AddNoteCommand.java
  src/main/java/jarvis/logic/commands/AddParticipationCommand.java
  src/main/java/jarvis/logic/commands/ClearCommand.java
  src/main/java/jarvis/logic/commands/DeleteNoteCommand.java
  src/main/java/jarvis/logic/commands/MarkLessonCommand.java
  src/main/java/jarvis/logic/commands/MarkStudentCommand.java
  src/main/java/jarvis/logic/commands/MasteryCheckCommand.java
  src/main/java/jarvis/logic/commands/UnmarkLessonCommand.java
  src/main/java/jarvis/logic/commands/UnmarkStudentCommand.java
  src/main/java/jarvis/logic/parser/MarkLessonCommandParser.java
  src/main/java/jarvis/logic/parser/UnmarkLessonCommandParser.java
  src/main/java/jarvis/ui/HelpWindow.java
Labels: priority.High

#105 Improve Ui to highlight timing conflicts between lessons
  src/main/java/jarvis/logic/LogicManager.java
  src/main/java/jarvis/logic/commands/AddConsultCommand.java
  src/main/java/jarvis/logic/commands/AddMasteryCheckCommand.java
  src/main/java/jarvis/logic/commands/AddStudioCommand.java
  src/main/java/jarvis/model/Lesson.java
  src/main/java/jarvis/model/LessonBook.java
  src/main/java/jarvis/model/UniqueStudentList.java
  src/main/java/jarvis/ui/ExpandedLessonListPanel.java
  src/main/java/jarvis/ui/LessonCard.java
  src/main/resources/view/ExpandedLessonCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/LessonCard.fxml
Labels: priority.High

#92 Lesson storage
  src/main/java/jarvis/MainApp.java
  src/main/java/jarvis/commons/util/JsonUtil.java
  src/main/java/jarvis/logic/LogicManager.java
  src/main/java/jarvis/model/Consult.java
  src/main/java/jarvis/model/Lesson.java
  src/main/java/jarvis/model/LessonAttendance.java
  src/main/java/jarvis/model/LessonBook.java
  src/main/java/jarvis/model/LessonDesc.java
  src/main/java/jarvis/model/LessonNotes.java
  src/main/java/jarvis/model/MasteryCheck.java
  src/main/java/jarvis/model/Model.java
  src/main/java/jarvis/model/Student.java
  src/main/java/jarvis/model/Studio.java
  src/main/java/jarvis/model/StudioParticipation.java
  src/main/java/jarvis/model/TimePeriod.java
  src/main/java/jarvis/model/UniqueLessonList.java
  src/main/java/jarvis/model/util/SampleLessonUtil.java
  src/main/java/jarvis/model/util/SampleStudentUtil.java
  src/main/java/jarvis/storage/JsonAdaptedConsult.java
  src/main/java/jarvis/storage/JsonAdaptedLesson.java
  src/main/java/jarvis/storage/JsonAdaptedMasteryCheck.java
  src/main/java/jarvis/storage/JsonAdaptedStudent.java
  src/main/java/jarvis/storage/JsonAdaptedStudio.java
  src/main/java/jarvis/storage/JsonAdaptedTask.java
  src/main/java/jarvis/storage/JsonLessonBookStorage.java
  src/main/java/jarvis/storage/JsonSerializableLessonBook.java
  src/main/java/jarvis/storage/JsonSerializableStudentBook.java
  src/main/java/jarvis/storage/JsonSerializableTaskBook.java
  src/main/java/jarvis/storage/JsonStudentBookStorage.java
  src/main/java/jarvis/storage/JsonTaskBookStorage.java
  src/main/java/jarvis/storage/LessonBookStorage.java
  src/main/java/jarvis/storage/Storage.java
  src/main/java/jarvis/storage/StorageManager.java
  src/main/java/jarvis/storage/StudentBookStorage.java
  src/main/java/jarvis/ui/ExpandedLessonCard.java
  src/main/java/jarvis/ui/UiManager.java
  src/main/resources/images/J.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/jarvis/commons/util/AppUtilTest.java
  src/test/java/jarvis/logic/LogicManagerTest.java
  src/test/java/jarvis/storage/JsonAdaptedStudentTest.java
  src/test/java/jarvis/storage/JsonSerializableTaskBookTest.java
  src/test/java/jarvis/storage/StorageManagerTest.java
Labels: priority.High
